name: HR Bot

on:
  schedule:
    # Morning Login (Mon–Sat)
    - cron: "55 3 * * 1-6"

    # Lunch Logout
    - cron: "30 7 * * 1-6"

    # Lunch Login
    - cron: "30 8 * * 1-6"

    # Evening Logout
    - cron: "20 13 * * 1-6"

  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Run Bot
        env:
          HR_USERNAME: ${{ secrets.HR_USERNAME }}
          HR_PASSWORD: ${{ secrets.HR_PASSWORD }}
          ACTION: login
        run: python hr_bot.py
