name: HR Logout

on:
  schedule:
    # 🕒 1:00 PM IST (07:30 UTC)
    - cron: "30 7 * * 1-6"

    # 🕒 7:00 PM IST (13:30 UTC)
    - cron: "30 13 * * 1-6"

  workflow_dispatch:

jobs:
  logout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Logout Bot
        run: python hr_bot.py
        env:
          HR_USERNAME: ${{ secrets.HR_USERNAME }}
          HR_PASSWORD: ${{ secrets.HR_PASSWORD }}
          ACTION: "logout"

      # 👇 ADD THIS AT END
      - name: Commit updated hours
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add hours.json
          git commit -m "update hours" || echo "No changes"
          git push
